CENTER_TILE = (996,593)
TILE_SIZE = (30,30)
PICK_TILE_BUTTON = (993,955)

COLOR_BUTTON_WIDTH = 73
COLOR_BUTTON_Y = 873
COLOR_BUTTON_START_X = 123

COLOR_MAX_INDEX = 24

COLOR_KEYS = [*"123456789abcdefghijklmnop"]

MAX_X_OFFSET = 1000
MAX_Y_OFFSET = 1000

IMAGE = """
ffffffffffffffffffffffffffedbbccbdeeffffffffffffffffffffffffffff
ffffffffffffffffffffffffebyyyyyyycccdfffffffffffffffffffffffffff
ffffffffffffffffffffffffbyayyycbbdddbeffffffffffffffffffffffffff
ffffffffffffffffffffffebyaycccbbcbdddeffffffffffffffffffffffffff
ffffffffffffffffffffffeaaaaayyyyayccdefffffffffffebeffffffffffff
fffffffffffffffffffffffecaaayyccccbbeffffffffffeeeccdeffffffffff
ffffffffffffffffffffffffdaaayyyccbbefffffffffecacbccccffffffffff
fffffffffffffffffffffffebaaaaayyycdffffffffffeaacedcccbeffffffff
fffffffffffffffffffffeddgedcyyycdeeeffffffffffcaayyyccccceffffff
ffffffffffeeeeeedddbbbbdeffdyyydefebdddddgeeeedaaaaaaaaaacffffff
fffffffedbbbbbbbbbccccbbeffeyyyeffdbddbbbbbbdddbaaaaaaaaydefffff
fffffffdcccccbbcccccccbbdffdyyydffdbbddbbbbbbbddbyaaycbdedcfffff
ffffffdyyyyccccccccccccbbdeyyyyyedcbbbdbbbbbcyyccbbbdddddbdfffff
fffffdyyyyyyccccccccccccbbbyyyyycbbbbbbbbbbbbyyyyyyccccbbbdfffff
ffffecyyyyyyyccccccccccccbbyyyyycbbbbbccbbbbbcyyyyycccbbbbdfffff
fffecyyyyyyaayyccccccccyccccyyyycbbbccccbbbbcccyyyyccbbbbbdfffff
ffecycycccyyayyyyccccccyccccccccbbbbccccbbcccccayyyycbbbbbbeffff
ffdycccccccdyayyyyccccyyccccccccbbbbbcccbccccdecyyyyccbbbbbgffff
fecyccccccdfbayyyyycccyyycccccccbbbbbbccbcccbfffdyyyycbbbbbdffff
fdccbdddbbefeaayyyycccbccyycccccbbbcccccbcccdffffdyyyccbbbbdffff
ebddeeeeeeeeebbcyyyyceeebcccycccbccccbccbcccefffffecyycbbbbeffff
dbbddddbbcbcbddddyyceeedcccccycbcccccbccccccefffffffedddeeffffff
fbyycccbaycaacddddceedcccccccccccccccbccbcccefffffffffffffffffff
ffedbccddcaaaacbdddedyycccccccccccccccccbcbbefffffffffffffffffff
ffffffedeedbcaaayyaaycccccccccbcccccccccbcbbefffffffffffffffffff
fffffffffffffdyyyyyyycccccccccccccccbcccccbbdfffffffffffffffffff
fffffffffffffdcyyyyyycycccccccccbcccbccbccbbbfffffffffffffffffff
fffffffffffffcyyyyyyyyyccccccccbcccbcccbcbbbbeffffffffffffffffff
ffffffffffffecyyyyyyyccccccccccbcccbccbbcbbbbeffffffffffffffffff
ffffffffffffdyyyyyyccccccccccccbccccccbbbbbbbeffffffffffffffffff
fffffffffffecyyyyyccccccccccbcccccccccbbbbbbbdffffffffffffffffff
fffffffffffdcyyyyccccccccycbcbbccccccbccbbbbbdffffffffffffffffff
fffffffffffbcyyyyccccccccycbcbbbbbbccbccbbbbbbefffffffffffffffff
ffffffffffecyyyyyccccccccycccbbbbbbccbbcbbbbbbefffffffffffffffff
ffffffffffdyyyyyyccccccccyyccccccccccbbbbbbbbbdfffffffffffffffff
ffffffffffffecyyycccccccccyccccccccccbbbbbbbbcbfffffffffffffffff
fffffffffffffdyyycccccccyyydedyyycccccbbbbbbddefffffffffffffffff
fffffffffffffecyyccccccccyyeffecaycccccbbbbbbdffffffffffffffffff
ffffffffffffffdyyyccccccccbfffffdyayccccbbbbbdefffffffffffffffff
ffffffffffffffeyyycccccccceffffffebaycccbbbbbddfffffffffffffffff
fffffffffffffffbyyyccccccdfffffffffdyyyccbbbbbdeffffffffffffffff
fffffffffffffffdyyycccccceffffffffffecyyccbbbbddffffffffffffffff
fffffffffffffffeyyycbcccbfffffffffffffbyyccbbbbdefffffffffffffff
ffffffffffffffffbyycbcccdffffffffffffffbyyccbbbdefffffffffffffff
ffffffffffffffffdyycbcccefffffffffffffffbyycbbbddfffffffffffffff
ffffffffffffffffecycbccbfffffffffffffffffbyycbbbdeffffffffffffff
fffffffffffffffffcycccceffffffffffffffffffbyycbbdgffffffffffffff
fffffffffffffffffcyycccefffffffffffffffffffdyycbbdefffffffffffff
fffffffffffffffffcyycccbffffffffffffffffffffeyycbbdfffffffffffff
fffffffffffffffffcyyyccceffffffffffffffffffffcyybbbdffffffffffff
fffffffffffffffffbyyycccbffffffffffffffffffffdyycbbbefffffffffff
fffffffffffffffffbyyyccccefffffffffffffffffffeyyybbbbeffffffffff
fffffffffffffffffdyyyccccbfffffffffffffffffffeyyycbbbdefffffffff
fffffffffffffffffeyyycccccefffffffffffffffffffcyyybbbbdfffffffff
fffffffffffffffffeyyyyccccbfffffffffffffffffffdyyycbbbdeffffffff
ffffffffffffffffffcyyyccccbgffffffffffffffffffeyyyybbbbdffffffff
ffffffffffffffffffecyyccbcdeffffffffffffffffffeyyyycbbbdgfffffff
ffffffffffffffffffecyyyccceffffffffffffffffffffcyyycbbbbdeffffff
fffffffffffffffedcyyacdeeefffffffffffffffffffffdcyyycbbdefffffff
fffffffffffeedcyyyycefffffffffffffffffffffffffffeyaayyycffffffff
ffffffffffecyyycbdeffffffffffffffffffffffffffffffeddcaaacdffffff
fffffffffffeeeeffffffffffffffffffffffffffffffffffffffdaaaacdefff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffedyaaycdee
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffebcyayb
"""